# TransiSafe 2.0 - Konfiguration

critical_power_margin_percent=10
critical_temperature_margin_c=10

output_file=results.csv
log_file=transisafe.log
transistor_database=transistors.csv
summary_file=summary.csv