import { useState } from "react";
import { Activity, Clock3, FileText, LoaderCircle, Play, RadioTower, SlidersHorizontal, X } from "lucide-react";
import type { AnalysisInput, Mode, RecentAnalysis } from "../types";

export function AnalysisActions({ input, mode, onModeChange, disabled, loading, hasResult, recentAnalyses, onOpenRecent, onRunWhatIf }: { input: AnalysisInput; mode: Mode; onModeChange: (mode: Mode) => void; disabled: boolean; loading: boolean; hasResult: boolean; recentAnalyses: RecentAnalysis[]; onOpenRecent: (analysis: RecentAnalysis) => void; onRunWhatIf: (scenario: AnalysisInput) => Promise<void> }) {
  const [historyOpen, setHistoryOpen] = useState(false);
  const [whatIfOpen, setWhatIfOpen] = useState(false);
  const [scenario, setScenario] = useState({ vds_v: input.vds_v, id_a: input.id_a, temperature_c: input.temperature_c });
  function openWhatIf() { setScenario({ vds_v: input.vds_v, id_a: input.id_a, temperature_c: input.temperature_c }); setHistoryOpen(false); setWhatIfOpen(true); }
  return <aside className="workflow-card action-card">
    <div className="workflow-heading"><span>3</span><h2>Analyse</h2><button className="history-trigger" type="button" onClick={() => setHistoryOpen((current) => !current)} aria-expanded={historyOpen} aria-label="Analyseverlauf öffnen" title="Zuletzt verwendete Analysen"><Clock3 size={16}/></button></div>
    <div className="analysis-mode"><span>Modus</span><div role="group" aria-label="Betriebsmodus"><button type="button" className={mode === "SWITCHING" ? "active" : ""} onClick={() => onModeChange("SWITCHING")}><RadioTower size={14}/>Switching</button><button type="button" className={mode === "LINEAR" ? "active" : ""} onClick={() => onModeChange("LINEAR")}><Activity size={14}/>Linear</button></div></div>
    <button className="run-analysis" form="operating-point-form" type="submit" disabled={disabled || loading}>{loading ? <LoaderCircle className="spin" size={17}/> : <Play size={17}/>}<span>{loading ? "C-Engine läuft…" : "Analyse starten"}</span></button>
    <button className="secondary-action" type="button" disabled={disabled || loading} onClick={openWhatIf}><SlidersHorizontal size={15}/>What-if-Modus</button>
    <button className="secondary-action report-action" type="button" disabled><FileText size={15}/>Bericht nach Analyse erstellen</button>
    <div className="last-analysis"><Clock3 size={15}/><div><span>Aktueller Status</span><b>{hasResult ? "Ergebnis verfügbar" : "Bereit zur Analyse"}</b></div></div>
    {historyOpen && <section className="recent-analysis-panel" aria-label="Zuletzt verwendete Analysen"><header><div><span>Analyseverlauf</span><b>Zuletzt verwendet</b></div><button type="button" onClick={() => setHistoryOpen(false)} aria-label="Verlauf schließen"><X size={15}/></button></header><div>{recentAnalyses.length === 0 ? <p>Noch keine Analyse ausgeführt.</p> : recentAnalyses.map((analysis) => <button className="recent-analysis-item" type="button" key={analysis.id} onClick={() => { onOpenRecent(analysis); setHistoryOpen(false); }}><span><b>{analysis.input.transistor_id}</b><small>{new Date(analysis.timestamp).toLocaleString("de-DE", { dateStyle: "short", timeStyle: "short" })}</small></span><strong>{analysis.input.vds_v} V · {analysis.input.id_a} A</strong><em>{analysis.result.result.status}</em></button>)}</div></section>}
    {whatIfOpen && <section className="what-if-panel" aria-label="What-if-Szenario"><header><div><span>What-if-Modus</span><b>Betriebspunkt variieren</b></div><button type="button" onClick={() => setWhatIfOpen(false)} aria-label="What-if-Modus schließen"><X size={15}/></button></header><p>Variiere die wichtigsten Belastungen. Das Szenario wird anschließend mit demselben C-Engine-Modell neu berechnet.</p><div className="what-if-fields"><label><span>VDS</span><div><input type="number" min="0" step="any" value={scenario.vds_v} onChange={(event) => setScenario((current) => ({ ...current, vds_v: Number(event.target.value) }))}/><b>V</b></div></label><label><span>ID</span><div><input type="number" min="0" step="any" value={scenario.id_a} onChange={(event) => setScenario((current) => ({ ...current, id_a: Number(event.target.value) }))}/><b>A</b></div></label><label><span>{input.temperature_reference === "CASE" ? "Tc" : "Ta"}</span><div><input type="number" step="any" value={scenario.temperature_c} onChange={(event) => setScenario((current) => ({ ...current, temperature_c: Number(event.target.value) }))}/><b>°C</b></div></label></div><div className="what-if-baseline"><span>Ausgangswert</span><b>{input.vds_v} V · {input.id_a} A · {input.temperature_c} °C</b></div><button className="what-if-run" type="button" disabled={loading || scenario.vds_v < 0 || scenario.id_a < 0} onClick={() => void onRunWhatIf({ ...input, ...scenario }).then(() => setWhatIfOpen(false))}>{loading ? <LoaderCircle className="spin" size={15}/> : <Play size={15}/>}Szenario analysieren</button></section>}
  </aside>;
}
