import { useEffect, useState, type FormEvent } from "react";
import { ArrowUpRight, CircleDot, FileText, HelpCircle, LogIn, Moon, Sun, UserCircle, X } from "lucide-react";
import type { EngineState, ModelSummary } from "../types";

type HeaderPanel = "help" | "documents" | "login" | null;
const API = import.meta.env.VITE_API_URL ?? "";

export function AppHeader({ engineState, apiDocsUrl, model }: { engineState: EngineState; apiDocsUrl: string; model: ModelSummary | null }) {
  const [theme, setTheme] = useState<"light" | "dark">(() => localStorage.getItem("transisafe-theme") === "dark" ? "dark" : "light");
  const [panel, setPanel] = useState<HeaderPanel>(null); const [user, setUser] = useState(""); const [authMode,setAuthMode]=useState<"login"|"register">("login"); const [authError,setAuthError]=useState("");
  const stateLabel = engineState === "checking" ? "C-ENGINE CHECK" : engineState === "ready" ? "C-ENGINE ONLINE" : "C-ENGINE OFFLINE";
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem("transisafe-theme", theme); }, [theme]);
  useEffect(() => { const token=localStorage.getItem("transisafe-session"); if(token) fetch(`${API}/api/auth/me`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.ok?r.json():Promise.reject()).then(data=>setUser(data.user.name)).catch(()=>localStorage.removeItem("transisafe-session")); },[]);
  useEffect(() => { function close(event: KeyboardEvent) { if (event.key === "Escape") setPanel(null); } window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, []);

  async function authenticate(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();setAuthError("");const data=new FormData(event.currentTarget);const body={email:String(data.get("email")??""),password:String(data.get("password")??""),...(authMode==="register"?{name:String(data.get("name")??"")}:{})};
    const response=await fetch(`${API}/api/auth/${authMode}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const payload=await response.json();if(!response.ok){setAuthError(payload.detail??"Anmeldung fehlgeschlagen");return;}localStorage.setItem("transisafe-session",payload.token);setUser(payload.user.name);setPanel(null);
  }
  async function signOut(){const token=localStorage.getItem("transisafe-session");if(token)await fetch(`${API}/api/auth/logout`,{method:"POST",headers:{Authorization:`Bearer ${token}`}});localStorage.removeItem("transisafe-session");setUser("");setPanel(null);}
  const initials = user ? user.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase() : "AK";

  return <><header className="app-header"><a className="header-brand" href="#top" aria-label="TransiSafe Analyze"><img className="header-mark" src="/transisafe-symbol-transparent.png" alt=""/><span><strong>Transi<span>Safe</span></strong><small>ENGINEERING DECISION SUPPORT</small></span></a><div className="header-actions"><span className={`engine-badge ${engineState}`}><CircleDot size={13}/>{stateLabel}</span><span className={`api-state ${engineState === "ready" ? "online" : ""}`}>API {engineState === "ready" ? "ONLINE" : "OFFLINE"}</span><a href={apiDocsUrl} target="_blank" rel="noreferrer">API DOCS <ArrowUpRight size={14}/></a><button className="header-icon-button" type="button" onClick={() => setTheme((current) => current === "light" ? "dark" : "light")} aria-label={theme === "light" ? "Dunkelmodus aktivieren" : "Hellmodus aktivieren"} title={theme === "light" ? "Dunkelmodus" : "Hellmodus"}>{theme === "light" ? <Moon size={18}/> : <Sun size={18}/>}</button><button className="header-icon-button" type="button" onClick={() => setPanel("help")} aria-label="Hilfe öffnen" title="Hilfe"><HelpCircle size={18}/></button><button className="header-icon-button" type="button" onClick={() => setPanel("documents")} aria-label="Dokumentenablage öffnen" title="Dokumentenablage"><FileText size={18}/></button><button className={`header-user-button ${user ? "signed-in" : ""}`} type="button" onClick={() => setPanel("login")} aria-label={user ? `Benutzer ${user}` : "Anmelden"} title={user || "Anmelden"}>{initials}</button></div></header>
    {panel && <div className="header-panel-overlay" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setPanel(null); }}><section className="header-panel" role="dialog" aria-modal="true" aria-labelledby="header-panel-title"><button className="panel-close" type="button" onClick={() => setPanel(null)} aria-label="Schließen"><X size={18}/></button>
      {panel === "help" && <><HelpCircle size={26}/><h2 id="header-panel-title">Hilfe zur Analyse</h2><p>Wähle ein Bauteil, trage den elektrischen Betriebspunkt ein, ergänze die thermischen Randbedingungen und starte anschließend die native Analyse.</p><ul><li><b>Komponente:</b> dokumentierte Bauteil- und Datenblattdaten</li><li><b>Betriebspunkt:</b> Eingaben für den C11-Rechenkern</li><li><b>Engineering Details:</b> Checks, Limits, Datenstatus und Traceability</li></ul></>}
      {panel === "documents" && <><FileText size={26}/><h2 id="header-panel-title">Dokumentenablage</h2><div className="document-list">{model ? <a href={model.datasheet_url} target="_blank" rel="noreferrer"><FileText size={17}/><span><b>{model.id}</b><small>Datenblatt · {model.revision}</small></span><ArrowUpRight size={15}/></a> : <p>Noch kein Bauteil ausgewählt.</p>}<article><FileText size={17}/><span><b>Analyseberichte</b><small>Über Export Results oder gespeicherte Analysen verfügbar</small></span></article></div></>}
      {panel === "login" && <>{user ? <><UserCircle size={28}/><h2 id="header-panel-title">Angemeldet</h2><p>Ingenieurkonto: <b>{user}</b></p><button className="panel-primary" type="button" onClick={() => void signOut()}>Abmelden</button></> : <form onSubmit={(event)=>void authenticate(event)}><LogIn size={28}/><h2 id="header-panel-title">{authMode==="login"?"Anmelden":"Konto erstellen"}</h2><div className="auth-switch"><button type="button" className={authMode==="login"?"active":""} onClick={()=>setAuthMode("login")}>Anmelden</button><button type="button" className={authMode==="register"?"active":""} onClick={()=>setAuthMode("register")}>Registrieren</button></div>{authMode==="register"&&<label>Name<input name="name" autoFocus required placeholder="Vor- und Nachname"/></label>}<label>E-Mail<input name="email" type="email" autoFocus={authMode==="login"} required placeholder="name@unternehmen.de"/></label><label>Passwort<input name="password" type="password" minLength={8} required placeholder="Mindestens 8 Zeichen"/></label>{authError&&<p className="auth-error">{authError}</p>}<button className="panel-primary" type="submit">{authMode==="login"?"Anmelden":"Konto erstellen"}</button></form>}</>}
    </section></div>}
  </>;
}
