import { useEffect, useState, type FormEvent } from "react";
import { ArrowUpRight, CircleDot, FileText, HelpCircle, LogIn, Moon, Sun, UserCircle, X } from "lucide-react";
import type { EngineState, ModelSummary } from "../types";

type HeaderPanel = "help" | "documents" | "login" | null;
type AuthUser = { name: string; email?: string; company?: string | null; avatar_url?: string | null; auth_provider?: string };
const API = import.meta.env.VITE_API_URL ?? "";

export function AppHeader({ engineState, apiDocsUrl, model }: { engineState: EngineState; apiDocsUrl: string; model: ModelSummary | null }) {
  const [theme, setTheme] = useState<"light" | "dark">(() => localStorage.getItem("transisafe-theme") === "dark" ? "dark" : "light");
  const [panel, setPanel] = useState<HeaderPanel>(null); const [user, setUser] = useState<AuthUser | null>(null); const [authMode,setAuthMode]=useState<"login"|"register">("login"); const [authError,setAuthError]=useState("");
  const stateLabel = engineState === "checking" ? "C-ENGINE CHECK" : engineState === "ready" ? "C-ENGINE ONLINE" : "C-ENGINE OFFLINE";
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem("transisafe-theme", theme); }, [theme]);
  useEffect(() => {
    const params=new URLSearchParams(window.location.search);const linkedinCode=params.get("linkedin_code");const linkedinError=params.get("linkedin_error");
    const cleanUrl=()=>{params.delete("linkedin_code");params.delete("linkedin_error");window.history.replaceState({},"",`${window.location.pathname}${params.size?`?${params}`:""}${window.location.hash}`);};
    if(linkedinError){setPanel("login");setAuthError("LinkedIn-Anmeldung wurde abgebrochen.");cleanUrl();return;}
    if(linkedinCode){fetch(`${API}/api/auth/linkedin/exchange`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:linkedinCode})}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.detail);return data;}).then(data=>{localStorage.setItem("transisafe-session",data.token);setUser(data.user);cleanUrl();}).catch(()=>{setPanel("login");setAuthError("LinkedIn-Anmeldung konnte nicht abgeschlossen werden.");cleanUrl();});return;}
    const token=localStorage.getItem("transisafe-session");if(token)fetch(`${API}/api/auth/me`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.ok?r.json():Promise.reject()).then(data=>setUser(data.user)).catch(()=>localStorage.removeItem("transisafe-session"));
  },[]);
  useEffect(() => { function close(event: KeyboardEvent) { if (event.key === "Escape") setPanel(null); } window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, []);

  async function authenticate(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();setAuthError("");const data=new FormData(event.currentTarget);const body={email:String(data.get("email")??""),password:String(data.get("password")??""),...(authMode==="register"?{name:String(data.get("name")??"")}:{})};
    const response=await fetch(`${API}/api/auth/${authMode}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const payload=await response.json();if(!response.ok){setAuthError(payload.detail??"Anmeldung fehlgeschlagen");return;}localStorage.setItem("transisafe-session",payload.token);setUser(payload.user);setPanel(null);
  }
  async function startLinkedIn(){setAuthError("");try{const response=await fetch(`${API}/api/auth/linkedin/status`);const status=await response.json();if(!status.configured){setAuthError("LinkedIn ist noch nicht konfiguriert. Client-ID und Secret müssen in der lokalen API hinterlegt werden.");return;}window.location.assign(`${API}/api/auth/linkedin/start`);}catch{setAuthError("LinkedIn-Anmeldung ist derzeit nicht erreichbar.");}}
  async function signOut(){const token=localStorage.getItem("transisafe-session");if(token)await fetch(`${API}/api/auth/logout`,{method:"POST",headers:{Authorization:`Bearer ${token}`}});localStorage.removeItem("transisafe-session");setUser(null);setPanel(null);}
  const initials = user ? user.name.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase() : "AK";

  return <><header className="app-header"><a className="header-brand" href="#top" aria-label="TransiSafe Analyze"><span><strong>Transi<span>Safe</span></strong><small>ENGINEERING DECISION SUPPORT</small></span></a><div className="header-actions"><span className={`engine-badge ${engineState}`}><CircleDot size={13}/>{stateLabel}</span><span className={`api-state ${engineState === "ready" ? "online" : ""}`}>API {engineState === "ready" ? "ONLINE" : "OFFLINE"}</span><a href={apiDocsUrl} target="_blank" rel="noreferrer">API DOCS <ArrowUpRight size={14}/></a><button className="header-icon-button" type="button" onClick={() => setTheme((current) => current === "light" ? "dark" : "light")} aria-label={theme === "light" ? "Dunkelmodus aktivieren" : "Hellmodus aktivieren"} title={theme === "light" ? "Dunkelmodus" : "Hellmodus"}>{theme === "light" ? <Moon size={18}/> : <Sun size={18}/>}</button><button className="header-icon-button" type="button" onClick={() => setPanel("help")} aria-label="Hilfe öffnen" title="Hilfe"><HelpCircle size={18}/></button><button className="header-icon-button" type="button" onClick={() => setPanel("documents")} aria-label="Dokumentenablage öffnen" title="Dokumentenablage"><FileText size={18}/></button><button className={`header-user-button ${user ? "signed-in" : ""}`} type="button" onClick={() => setPanel("login")} aria-label={user ? `Benutzer ${user.name}` : "Anmelden"} title={user?.name || "Anmelden"}>{user?.avatar_url?<img src={user.avatar_url} alt="" referrerPolicy="no-referrer"/>:initials}</button></div></header>
    {panel && <div className="header-panel-overlay" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setPanel(null); }}><section className="header-panel" role="dialog" aria-modal="true" aria-labelledby="header-panel-title"><button className="panel-close" type="button" onClick={() => setPanel(null)} aria-label="Schließen"><X size={18}/></button>
      {panel === "help" && <><HelpCircle size={26}/><h2 id="header-panel-title">Hilfe zur Analyse</h2><p>Wähle ein Bauteil, trage den elektrischen Betriebspunkt ein, ergänze die thermischen Randbedingungen und starte anschließend die native Analyse.</p><ul><li><b>Komponente:</b> dokumentierte Bauteil- und Datenblattdaten</li><li><b>Betriebspunkt:</b> Eingaben für den C11-Rechenkern</li><li><b>Engineering Details:</b> Checks, Limits, Datenstatus und Traceability</li></ul></>}
      {panel === "documents" && <><FileText size={26}/><h2 id="header-panel-title">Dokumentenablage</h2><div className="document-list">{model ? <a href={model.datasheet_url} target="_blank" rel="noreferrer"><FileText size={17}/><span><b>{model.id}</b><small>Datenblatt · {model.revision}</small></span><ArrowUpRight size={15}/></a> : <p>Noch kein Bauteil ausgewählt.</p>}<article><FileText size={17}/><span><b>Analyseberichte</b><small>Über Export Results oder gespeicherte Analysen verfügbar</small></span></article></div></>}
      {panel === "login" && <>{user ? <div className="signed-in-profile">{user.avatar_url?<img src={user.avatar_url} alt="" referrerPolicy="no-referrer"/>:<UserCircle size={42}/>}<div><h2 id="header-panel-title">{user.name}</h2>{user.company&&<p>{user.company}</p>}<small>{user.auth_provider==="linkedin"?"Über LinkedIn angemeldet":"Lokales Ingenieurkonto"}</small></div><button className="panel-primary" type="button" onClick={() => void signOut()}>Abmelden</button></div> : <form onSubmit={(event)=>void authenticate(event)}><LogIn size={28}/><h2 id="header-panel-title">{authMode==="login"?"Anmelden":"Konto erstellen"}</h2><div className="auth-switch"><button type="button" className={authMode==="login"?"active":""} onClick={()=>setAuthMode("login")}>Anmelden</button><button type="button" className={authMode==="register"?"active":""} onClick={()=>setAuthMode("register")}>Registrieren</button></div>{authMode==="register"&&<label>Name<input name="name" autoFocus required placeholder="Vor- und Nachname"/></label>}<label>E-Mail<input name="email" type="email" autoFocus={authMode==="login"} required placeholder="name@unternehmen.de"/></label><label>Passwort<input name="password" type="password" minLength={8} required placeholder="Mindestens 8 Zeichen"/></label><button className="panel-primary" type="submit">{authMode==="login"?"Anmelden":"Konto erstellen"}</button><div className="auth-divider"><span>oder</span></div><button className="linkedin-auth" type="button" onClick={()=>void startLinkedIn()}><b>in</b><span>Mit LinkedIn anmelden</span></button><small className="linkedin-note">Name und Profilbild werden übernommen. Firma nur, wenn LinkedIn sie für die App freigibt.</small>{authError&&<p className="auth-error">{authError}</p>}</form>}</>}
    </section></div>}
  </>;
}
