import { AlertTriangle, ArrowRight, Columns3, Download, FileSpreadsheet, Search, Upload } from "lucide-react";
import { useState } from "react";
import type { AnalysisInput, AnalysisResponse } from "../types";

const API = import.meta.env.VITE_API_URL ?? "";
type Preview = { filename:string; columns:string[]; suggested_mapping:Record<string,string|null>; row_count:number; raw_rows:Record<string,unknown>[] };
type Validation = { detected:number; ready:number; warnings:number; invalid:number; valid_rows:{source_row:number;analysis_name:string;input:AnalysisInput}[]; invalid_rows:{source_row:number;errors:string[]}[] };
type BatchResult = { source_row:number; analysis_name:string; input:AnalysisInput; result?:AnalysisResponse; error?:string };
type ColumnKey = "row"|"analysis"|"component"|"mode"|"vds"|"id"|"assessment"|"limit"|"tj"|"loss"|"warnings";
const fields=["analysis_name","transistor_id","mode","vds_v","id_a","pulse_duration_us","duty_cycle_percent","frequency_khz","gate_drive_voltage_v","e_on_uj","e_off_uj","case_temperature_c","ambient_temperature_c","temperature_reference","rth_cs_k_per_w","rth_sa_k_per_w","safety_factor"];
const columnLabels:Record<ColumnKey,string>={row:"Row",analysis:"Analysis",component:"Component",mode:"Mode",vds:"VDS",id:"ID",assessment:"Assessment",limit:"Relevant limit",tj:"Tj",loss:"Total loss",warnings:"Warnings"};
const columnWidths:Record<ColumnKey,string>={row:"55px",analysis:"1.2fr",component:"1fr",mode:"85px",vds:"75px",id:"75px",assessment:"130px",limit:"140px",tj:"90px",loss:"95px",warnings:"70px"};

export function BatchWorkspace({ onOpen }: { onOpen: (input: AnalysisInput, result: AnalysisResponse) => void }) {
  const [preview,setPreview]=useState<Preview|null>(null); const [mapping,setMapping]=useState<Record<string,string|null>>({}); const [validation,setValidation]=useState<Validation|null>(null); const [results,setResults]=useState<BatchResult[]>([]);
  const [filter,setFilter]=useState("ALL"); const [search,setSearch]=useState(""); const [sort,setSort]=useState("row"); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [selected,setSelected]=useState<Set<number>>(new Set());
  const [visibleColumns,setVisibleColumns]=useState<Set<ColumnKey>>(new Set(Object.keys(columnLabels) as ColumnKey[]));

  async function upload(file:File) { setBusy(true);setError("");try{const response=await fetch(`${API}/api/batch/preview?filename=${encodeURIComponent(file.name)}`,{method:"POST",headers:{"Content-Type":"application/octet-stream"},body:await file.arrayBuffer()});const data=await response.json();if(!response.ok)throw new Error(data.detail);setPreview(data);setMapping(data.suggested_mapping);setValidation(null);setResults([]);setSelected(new Set());}catch(reason){setError(reason instanceof Error?reason.message:"Datei konnte nicht gelesen werden");}finally{setBusy(false);} }
  async function validate(){if(!preview)return;const response=await fetch(`${API}/api/batch/validate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rows:preview.raw_rows,mapping})});const data=await response.json();if(!response.ok){setError(data.detail);return;}setValidation(data);}
  async function analyze(){if(!validation?.ready)return;setBusy(true);const response=await fetch(`${API}/api/batch/analyze`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rows:validation.valid_rows})});const data=await response.json();setResults(data.results??[]);setBusy(false);}
  async function exportBatch(selectionOnly=false){const exported=selectionOnly?results.filter(row=>selected.has(row.source_row)):results;if(!exported.length)return;const response=await fetch(`${API}/api/batch/export`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({results:exported})});if(!response.ok)return;const blob=await response.blob(),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download=selectionOnly?"TransiSafe-Batch-Selected.xlsx":"TransiSafe-Batch-Results.xlsx";anchor.click();URL.revokeObjectURL(url);}

  function matchesEngineeringFilter(row:BatchResult){const status=row.result?.result.status??"UNKNOWN",constraint=row.result?.result.closest_constraint.type;
    if(filter==="ALL")return true;if(filter==="PASS")return status==="SAFE";if(filter==="WARNING")return status==="CRITICAL";if(filter==="FAIL")return status.startsWith("NOT_SAFE");if(filter==="UNKNOWN")return status==="INSUFFICIENT_DATA"||!row.result;
    if(filter==="SOA")return constraint==="SOA"||status==="NOT_SAFE_SOA";if(filter==="THERMAL")return constraint==="TEMPERATURE"||status.includes("TEMPERATURE")||status==="NOT_SAFE_BOTH";if(filter==="VOLTAGE")return constraint==="VOLTAGE"||status==="NOT_SAFE_VOLTAGE";if(filter==="CURRENT")return constraint==="CURRENT"||status==="NOT_SAFE_CURRENT";return filter==="DATA_INCOMPLETE"&&!row.result?.result.data_complete;
  }
  const visible=results.filter(matchesEngineeringFilter).filter(row=>`${row.analysis_name} ${row.input.transistor_id}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==="status"?(a.result?.result.status??"").localeCompare(b.result?.result.status??""):sort==="constraint"?(a.result?.result.closest_constraint.reserve_percent??999)-(b.result?.result.closest_constraint.reserve_percent??999):a.source_row-b.source_row);
  const columns=(Object.keys(columnLabels) as ColumnKey[]).filter(key=>visibleColumns.has(key)); const gridTemplate=columns.map(key=>columnWidths[key]).join(" ");
  function cell(row:BatchResult,key:ColumnKey){switch(key){case"row":return row.source_row;case"analysis":return <b>{row.analysis_name}</b>;case"component":return row.input.transistor_id;case"mode":return row.input.mode;case"vds":return `${row.input.vds_v} V`;case"id":return `${row.input.id_a} A`;case"assessment":return <em>{row.result?.result.status??"ERROR"}</em>;case"limit":return row.result?`${row.result.result.closest_constraint.type} ${row.result.result.closest_constraint.reserve_percent.toFixed(1)}%`:"—";case"tj":return row.result?`${row.result.result.tj_c.toFixed(1)} °C`:"—";case"loss":return row.result?`${row.result.result.p_total_w.toFixed(2)} W`:"—";case"warnings":return row.result?.analysis_metadata.warnings.length??1;}}

  return <main className="secondary-workspace"><header className="page-title"><div><span>NATIVE BATCH WORKFLOW</span><h1>Batch Analysis</h1><p>UPLOAD → MAP → VALIDATE → ANALYZE → REVIEW → DRILL DOWN → EXPORT</p></div><FileSpreadsheet size={28}/></header>
    <section className="batch-toolbar"><a href={`${API}/api/batch/template`}><Download size={16}/>Batch Template.xlsx</a><label className="upload-button"><Upload size={16}/>{busy?"Verarbeitung…":"CSV oder XLSX hochladen"}<input type="file" accept=".csv,.xlsx" disabled={busy} onChange={(event)=>{const file=event.target.files?.[0];if(file)void upload(file);}}/></label>{preview&&<b>{preview.row_count} Zeilen erkannt</b>}</section>{error&&<p className="analysis-error"><AlertTriangle size={15}/>{error}</p>}
    {preview&&!validation&&<section className="mapping-card"><header><h2>Spalten zuordnen</h2><button onClick={()=>void validate()}>Validieren<ArrowRight size={15}/></button></header><div className="mapping-list">{preview.columns.map(column=><label key={column}><span>{column}</span><ArrowRight size={14}/><select value={mapping[column]??""} onChange={(event)=>setMapping(current=>({...current,[column]:event.target.value||null}))}><option value="">— ignorieren</option>{fields.map(field=><option value={field} key={field}>{field}</option>)}</select><em className={mapping[column]?"mapped":"ignored"}>{mapping[column]?"✓ mapped":"— ignored"}</em></label>)}</div></section>}
    {validation&&results.length===0&&<section className="validation-card"><div><strong>{validation.detected}</strong><span>erkannt</span></div><div className="ready"><strong>{validation.ready}</strong><span>bereit</span></div><div className="warning"><strong>{validation.warnings}</strong><span>Warnungen</span></div><div className="invalid"><strong>{validation.invalid}</strong><span>ungültig</span></div><button disabled={!validation.ready||busy} onClick={()=>void analyze()}>Analyze {validation.ready} valid operating points</button>{validation.invalid_rows.length>0&&<details><summary>Ungültige Zeilen anzeigen</summary>{validation.invalid_rows.map(row=><p key={row.source_row}>Zeile {row.source_row}: {row.errors.join(" · ")}</p>)}</details>}</section>}
    {results.length>0&&<section className="batch-results"><header className="batch-results-toolbar"><div className="result-filters">{["ALL","PASS","WARNING","FAIL","UNKNOWN","SOA","THERMAL","VOLTAGE","CURRENT","DATA_INCOMPLETE"].map(value=><button className={filter===value?"active":""} onClick={()=>setFilter(value)} key={value}>{value.replace("_"," ")}</button>)}</div><div className="batch-tools"><label><Search size={14}/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Suchen"/></label><select value={sort} onChange={event=>setSort(event.target.value)} aria-label="Sortierung"><option value="row">Row</option><option value="status">Status</option><option value="constraint">Closest constraint</option></select><details className="column-picker"><summary><Columns3 size={14}/>Spalten</summary><div>{(Object.keys(columnLabels) as ColumnKey[]).map(key=><label key={key}><input type="checkbox" checked={visibleColumns.has(key)} onChange={event=>setVisibleColumns(current=>{const next=new Set(current);event.target.checked?next.add(key):next.delete(key);return next;})}/>{columnLabels[key]}</label>)}</div></details></div><div className="batch-export-buttons"><button disabled={!selected.size} onClick={()=>void exportBatch(true)}><Download size={15}/>Selected ({selected.size})</button><button onClick={()=>void exportBatch()}><Download size={15}/>Export All</button></div></header><div className="batch-table"><div className="batch-head" style={{gridTemplateColumns:`28px ${gridTemplate}`}}><span></span>{columns.map(key=><span key={key}>{columnLabels[key]}</span>)}</div>{visible.map(row=><div className="batch-row" key={row.source_row} style={{gridTemplateColumns:`28px ${gridTemplate}`}}><input type="checkbox" checked={selected.has(row.source_row)} aria-label={`Zeile ${row.source_row} auswählen`} onChange={event=>setSelected(current=>{const next=new Set(current);event.target.checked?next.add(row.source_row):next.delete(row.source_row);return next;})}/>{columns.map(key=><button className="batch-cell" type="button" key={key} disabled={!row.result} onClick={()=>row.result&&onOpen(row.input,row.result)}>{cell(row,key)}</button>)}</div>)}</div></section>}
  </main>;
}
