import { Copy, Download, History, Pencil, Play, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import type { SavedAnalysis } from "../types";

const API = import.meta.env.VITE_API_URL ?? "";
export function SavedAnalyses({ refreshToken, onOpen }: { refreshToken: number; onOpen: (analysis: SavedAnalysis) => void }) {
  const [items, setItems] = useState<SavedAnalysis[]>([]); const [error, setError] = useState("");
  async function refresh() { try { const response=await fetch(`${API}/api/analyses`); if(!response.ok) throw new Error(); setItems((await response.json()).analyses); } catch { setError("Gespeicherte Analysen konnten nicht geladen werden."); } }
  useEffect(() => { void refresh(); }, [refreshToken]);
  async function action(id: string, kind: "duplicate"|"rerun"|"delete") { const response=await fetch(`${API}/api/analyses/${id}${kind === "duplicate" ? "/duplicate" : kind === "rerun" ? "/rerun" : ""}`, { method: kind === "delete" ? "DELETE" : "POST" }); if(response.ok) void refresh(); }
  async function rename(item: SavedAnalysis) { const name=window.prompt("Neuer Name",item.name)?.trim(); if(!name||name===item.name)return; const response=await fetch(`${API}/api/analyses/${item.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,input:item.input,result:item.result,parent_id:item.parent_id})}); if(response.ok)void refresh(); }
  function download(id: string, format: string) { window.open(`${API}/api/analyses/${id}/export/${format}`, "_blank", "noopener,noreferrer"); }
  return <main className="secondary-workspace"><header className="page-title"><div><span>ENGINEERING WORKFLOW</span><h1>Gespeicherte Analysen</h1><p>Bestehende Betriebspunkte öffnen, duplizieren, verändern und erneut durch die native Engine ausführen.</p></div><History size={27}/></header>
    {error && <p className="analysis-error">{error}</p>}{items.length === 0 ? <section className="empty-library"><History size={34}/><h2>Noch keine Analyse gespeichert</h2><p>Speichere einen berechneten Betriebspunkt auf der Analyze-Seite.</p></section> : <section className="saved-table"><div className="saved-head"><span>Name</span><span>Komponente</span><span>Betriebspunkt</span><span>Status</span><span>Aktualisiert</span><span>Aktionen</span></div>{items.map((item) => <article key={item.id}><button className="saved-name" type="button" onClick={() => onOpen(item)}><b>{item.name}</b><small>{item.parent_id ? `Abgeleitet von ${item.parent_id.slice(0,8)}` : item.id.slice(0,8)}</small></button><span>{item.input.transistor_id}</span><span>{item.input.vds_v} V · {item.input.id_a} A · {item.input.temperature_c} °C</span><b className={`table-status ${item.result.result.status.toLowerCase()}`}>{item.result.result.status}</b><time>{new Date(item.updated_at).toLocaleString("de-DE")}</time><div className="row-actions"><button title="Rerun" onClick={() => void action(item.id,"rerun")}><Play size={15}/></button><button title="Umbenennen" onClick={() => void rename(item)}><Pencil size={15}/></button><button title="Duplizieren" onClick={() => void action(item.id,"duplicate")}><Copy size={15}/></button><button title="Excel exportieren" onClick={() => download(item.id,"xlsx")}><Download size={15}/></button><button title="Löschen" onClick={() => void action(item.id,"delete")}><Trash2 size={15}/></button></div></article>)}</section>}
  </main>;
}
